wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.3
    framework: keras
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.9.16
    start_time: 1678718259.747331
    t:
      1:
      - 2
      - 3
      - 55
      2:
      - 2
      - 3
      - 55
      3:
      - 3
      - 8
      - 19
      - 23
      4: 3.9.16
      5: 0.13.3
      8:
      - 3
      - 5
      10:
      - 9
batch_size:
  desc: null
  value: 128
digits:
  desc: null
  value: 5
hidden_size:
  desc: null
  value: 128
training_size:
  desc: null
  value: 50000
